### ISSUE TITLE
Can't hide side panel.

### ISSUE THREAD

**Issue by SkysCrystal** [notion-enhancer/notion-enhancer#581] opened 2021-09-11 12:29 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Can't hide Outliner in side panel.

**expected behaviour**
Can not hide outliner. I've tried to reopen this function.

**screenshots**
![image](https://user-images.githubusercontent.com/49473463/132947842-5780b617-1086-4083-aef4-43dcadf704ea.png)

**platform**
windows 10

**Comment by ayush729p** [comment] 2021-09-11 15:58
Duplicate of #578. You can follow the updates there.

You can close this issue to avoid redundancy if your issue is the same.

**Closed** 2021-09-12 01:50 UTC
Labels: bug
