### ISSUE TITLE
Do not have permissions to open the application

### ISSUE THREAD

**Issue by dcmba** [notion-enhancer/notion-enhancer#357] opened 2020-12-22 18:42 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
I ran the installer and it appeared to run to completion. I restarted my mac. When I opened Notion, it said I do not have permissions to open the application Notion and to contact my system admin.

**expected behaviour**
I expected the enhancer to work with notion as described

**screenshots**
if applicable, add screenshots of your problem.

**platform**
macOS

**Comment by dragonwocky** [comment] 2020-12-22 23:21
duplicate of https://github.com/notion-enhancer/notion-enhancer/issues/355

run `codesign --force --deep --sign - /Applications/Notion.app` in terminal to fix

**Closed by dragonwocky** 2020-12-22 23:21 UTC
Labels: bug, duplicate
