### ISSUE TITLE
Using too much memory and not being released causes problems with my computer

### ISSUE THREAD

**Issue by GuYith** [notion-enhancer/notion-enhancer#529] opened 2021-07-07 12:28 UTC
Using too much memory and not being released causes problems with my computer. When I open the Task Manager, I notice that Notions are running out of memory. This is a problem I have after installing this plugin.  

windows 10

**Comment by Emonadeo** [comment] 2021-07-09 00:11
I am also ran into the same issue twice recently. Though I don't know whether it's caused by Notion itself or notion-enhancer.

![image](https://user-images.githubusercontent.com/13782948/125004861-b7c8ca00-e05a-11eb-90e9-4ae913f29835.png)

**Comment by MrKebab362** [comment] 2021-07-10 03:39
Same here. With notion-enhancer (no themes turned on, 'custom icon sets'  is turned on) the CPU and RAM usage is way too high. 
![image](https://user-images.githubusercontent.com/66750903/125150586-c84f7200-e138-11eb-96e2-89905116528d.png)

**Comment by xaa** [comment] 2021-07-17 14:26
seems a duplicate of #333 
(have you the "close windo to the tray" option on ? give a try without it)

**Closed** 2021-10-07 06:00 UTC
Labels: bug, duplicate
