### ISSUE TITLE
Loading Notion

### ISSUE THREAD

**Issue by rofllmao5423** [notion-enhancer/notion-enhancer#255] opened 2020-11-14 09:10 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
I start the app (Notion) and it does not load. (I use the enhancer). There is only the functioning loading symbol (The loading symbol is not frozen). 
I wait for 10 min and longer but nothing happens. I relaunch notion and/or restart my computer-sometimes I get lucky and it loads- a lot of times it doesn't. 
Opening the Enhancements (Alt+E) doesn't work either when Notion is not loaded. This page also shows the functioning loading symbol.

**expected behaviour**
Notion should load and show any of my pages.

**screenshots**
![image](https://user-images.githubusercontent.com/73342623/99143796-a876b580-2660-11eb-8b5d-a338c371bfae.png)

**platform**
 windows 10

**Comment by dragonwocky** [comment] 2020-11-14 09:22
duplicate of #197

fix will be released soon, best workaround at the moment is:

Open notion in your browser
Create a new page
Click on the 3 dots on the top right and click "Open in Windows app"

**Closed by dragonwocky** 2020-11-14 09:22 UTC
Labels: bug
