### ISSUE TITLE
Notion Enhancer crashes after setting sans font to Noto Sans

### ISSUE THREAD

**Issue by asa9ohan** [notion-enhancer/notion-enhancer#305] opened 2020-12-02 17:03 UTC
**describe the bug**
Changed font chooser, scroll up, and various other settings in enhancement settings window, then upon relaunching Notion crashes. When I try to open Notion again, it displays without any enhancements (notion enhancer isn't launching). I try to install notion enhancer again through the command prompt using the same installation command as before, and no issues occur (it says one package was updated), but when I open up Notion it's a blank (white) window. I can see notion-enhancer running in the tray, and when I click enhancements the settings window opens but it's also blank (white).

**Update:**
Uninstalled notion-enhancer using instructions on GitHub page, then reinstalled, but same issues occur.

**Update 2:**
Found /.notion-enhancer folder with a bunch of .JSON files, one of them contained `{sans: "Noto Sans"}`, so I tried deleting it and restarting Notion, didn't work.

**Update 3:**
Found Kirakeru's solution on another thread about a white window issue #298 , and it works for me.

**expected behaviour**
Notion window opens as usual.

**screenshots**
![image](https://user-images.githubusercontent.com/62686118/100906160-38937680-350c-11eb-9f49-f5552445c80a.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment] 2020-12-02 19:51
duplicate of #298, unrelated to noto sans

**Closed by dragonwocky** 2020-12-02 19:51 UTC
Labels: bug, duplicate
