### ISSUE TITLE
Updates on web version(extension maybe?) for chrome/ff etc.

### ISSUE THREAD

**Issue by surajmandalcell** [notion-enhancer/notion-enhancer#316] opened 2020-12-05 08:44 UTC
** problem **

I've been using notion-enhancer on mac but it keeps crashing, might be my system or some other issue but still, I'd prefer working on web version since it will be easier to customize without risk of crashes and stuff.

**solution**

Web Extension

**cons**

Will take development time.

**alternatives**

Temporarily, scripts?

**Comment by dragonwocky** [comment] 2020-12-05 08:55
the web version will not come until after the desktop hack reaches v1.0.0, which is still a few months off at least.

some of the features (e.g. right to left text, custom inserts) can be done by already existing extensions until then, but if you want the enhancer use the app. if it's crashing and you can find any error messages or steps to reproduce the crash then please open a separate issue for that.

closing this because it's already written about elsewhere and no actions will be taken directly from this issue.

**Closed by dragonwocky** 2020-12-05 08:55 UTC
Labels: enhancement
