### ISSUE TITLE
Emoji sets achieve without user agent on MacOS breaks extension on Windows.

### ISSUE THREAD

**Issue by kursorbyte** [notion-enhancer/notion-enhancer#361] opened 2020-12-27 17:04 UTC
*Already mentioned this, but I have opened this issue for recording and tracking purposes*

**describe the bug**
See message from Discord server here: https://discord.com/channels/748161877045149706/748162434237202472/773330948447535134
In short, changing emojis doesn't reflect immediately.

**expected behaviour**
Changing the icon should do so immediately.

**findings**
It was working in an older version so I looked at a previous version of the *mod.js* for the extension. The most recent one that works as intended is v0.2.0 (https://github.com/notion-enhancer/notion-enhancer/commit/840f9940819b7be4c445eb9f2e0bf957646b38f1) of the emoji set extension where changes were made so MacOS would use Windows' user agent. The next version, v0.3.0 (https://github.com/notion-enhancer/notion-enhancer/commit/481500c5636c71a3341083a3892acf05c89a0f83), is the one that exhibits the delay in change. Changes were made so the extension no longer modifies the user agent so MacOS hotkeys like cmd work. These changes and edits in the code cause the delay. (note: I have no knowledge of JavaScript)

**temporary fix**
Download v0.2.0 of *mod.js* https://raw.githubusercontent.com/notion-enhancer/notion-enhancer/840f9940819b7be4c445eb9f2e0bf957646b38f1/mods/emoji-sets/mod.js and locate: C:\Users\%username%\AppData\Roaming\npm\node_modules\notion-enhancer\mods\emoji-sets. Rename the current mod.js to mod_original.js (for restoration purposes if anything goes wrong) and put the downloaded file there.

**screenshots**
![49e3Pb4ue64Es](https://user-images.githubusercontent.com/74338929/103175796-b3fdf480-483a-11eb-8e4e-c773d5d2ce0a.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment] 2020-12-27 22:44
@kursorbyte instant changing was a benefit of the previous method that is unfortunately no longer available, but the expected behaviour is that changes (e.g. enabled/disabling or configuring) will not take full effect until after an app relaunch (as the menu says up the top whenever you make a change). Since this is actually working as intended, I'm closing this issue.

**Comment by kursorbyte** [comment] 2020-12-27 23:41
@dragonwocky Thanks for the clarification.

**Closed** 2020-12-28 03:05 UTC
Labels: bug, invalid
