### ISSUE TITLE
Tabs do not display page name

### ISSUE THREAD

**Issue by aligracegustin** [notion-enhancer/notion-enhancer#271] opened 2020-11-18 18:09 UTC
**describe the bug**
My tabs don't show the page name like in your examples, each tab just says "NOTION.SO". I am using the Notion desktop client on Mac. 

**expected behaviour**
I would like to see each page name in the tab which is the case in the example screenshots you show (although these could just be mock ups). 

**screenshots**
![Screen Shot 2020-11-18 at 10 07 14 AM](https://user-images.githubusercontent.com/50428726/99569721-d708cf00-2985-11eb-91c8-6b8cbd65faa9.png)

**platform**
macOS Catalina Version 10.15.7 (19H2)

**Comment by aligracegustin** [comment] 2020-11-18 19:16
This actually just started working so closing!

**Comment by dragonwocky** [comment] 2020-11-18 21:14
duplicate of https://github.com/notion-enhancer/notion-enhancer/issues/196

**Closed by dragonwocky** 2020-11-18 21:14 UTC
Labels: bug

**Comment by dmercado2001** [comment] 2021-01-26 20:27
I am operating on MacOS Big Sur 11.1 
There is a possibility this change happened when there was an update from Big Sur 11.0 to 11.1
