### ISSUE TITLE
Closing tabs animation

### ISSUE THREAD

**Issue by Theguyhere0** [notion-enhancer/notion-enhancer#356] opened 2020-12-21 22:43 UTC
**describe the bug**
When there are multiple tabs open, closing any tab will cause the left-most tab to shrink as if it were being closed before reopening.
If the left-most tab is open when the other tab is closed, then the second-to-left-most tab will shrink.

**expected behaviour**
The tab that is being closed should be the tab that is animated and shrinks.

**screenshots**
https://user-images.githubusercontent.com/52550799/102829891-eb812280-439c-11eb-9034-839ba63d5984.mp4

**platform**
Windows 10

**Comment by admiraldus** [comment] 2020-12-21 22:44
taking screenshots can be difficult but how about taking a gif?

**Comment by Theguyhere0** [comment] 2020-12-21 23:00
> taking screenshots can be difficult but how about taking a gif?

Oh yeah, good point I put a video there to show it.

**Comment by admiraldus** [comment] 2020-12-21 23:07
> > taking screenshots can be difficult but how about taking a gif?
> 
> Oh yeah, good point I put a video there to show it.

i guess it's due to the auto-shrink system in tabs but there was no such problem when i tested it. seems to be caused by weird delay when closing the tab. i'll test this in my notion. let's see if what happens to you will also happen to me...

**Closed** 2021-10-07 05:39 UTC
Labels: bug
