### ISSUE TITLE
Notion window doesn't open when clicking on the app icon in dock

### ISSUE THREAD

**Issue by DSimpson-Shah** [notion-enhancer/notion-enhancer#427] opened 2021-02-18 17:16 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When Notion (together with Notion Enhancer) has been running for some time (around 10 minutes+), it is no longer possible to open the Notion window by clicking on the app icon in the dock. Rather, you have to quit the app and relaunch it, or use the re-launch option in the Notion Enhancer menu in the task bar.

**expected behaviour**
The Notion window should open when the dock icon is clicked upon. Unless if using Notion Enhancer purposely prevents this.
[Screen Recording 2021-02-18 at 17.10.09.zip](https://github.com/notion-enhancer/notion-enhancer/files/6004643/Screen.Recording.2021-02-18.at.17.10.09.zip)

**screenshots**
Please see attached screen shot video

**platform**
MacOS 11.2.1

**Comment by dragonwocky** [comment] 2021-02-18 17:28
are you right- or left-clicking on the dock icon?

**Comment by DSimpson-Shah** [comment] 2021-02-18 17:54
I'm left clicking

**Comment by Jasminecbrown91** [comment] 2021-02-22 19:27
I've had this same issue happen to where I had to create a shortcut and add it back into my dock.

**Comment by DSimpson-Shah** [comment] 2021-02-23 20:18
@Jasminecbrown91 Thanks for that info. Could you elaborate please? Do you mean a web shortcut?

**Comment by Jasminecbrown91** [comment] 2021-02-23 23:13
hmm, I’m trying to remember what I did. I’ve been having issues with
Notion. Every time I restart my Mac, it stops working altogether. It’s been
quite frustrating.

However, for that weird icon issue, I believe I went into my applications
folder or or the launchpad and dragged it onto my toolbar…therefore
creating a “shortcut”.

Hope that helps!

-Jasmine

**Comment by youngster** [comment] 2021-04-14 09:29
i have the same issue happened，when i got first installed

**Comment by youngster** [comment] 2021-04-19 12:14
https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

use this resolved

**Comment by dragonwocky** [comment] 2021-04-19 12:18
@youngster this is a different issue caused by some win10-aimed window operations that break things a bit on mac since it treats closed windows differently.

when the enhancer is "not opening", it actually is opening, it's just in a hidden and so unusable state after when you last closed it. you should be able to bring it back via `cmd+shift+a`.

**Comment by justamanm** [comment] 2021-04-27 07:30
i meet the same issue, `ctrl+shift+n` works on win10

**Closed** 2021-10-07 05:51 UTC
Labels: bug
