### ISSUE TITLE
macos no perms to open notion

### ISSUE THREAD

**Issue by jmiao24** [notion-enhancer/notion-enhancer#253] opened 2020-11-12 21:53 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
I can not open notion if restart the computer after installing the enhancer.

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.
<img width="248" alt="Screen Shot 2020-11-12 at 3 53 05 PM" src="https://user-images.githubusercontent.com/56059516/99000603-27ec7380-24ff-11eb-91e2-5eb2b1cf2cd1.png">

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
macOS

**Comment by Davedeji** [comment] 2020-11-13 04:59
had the same issue since lates notion enhancer version, first on catalina and now on big sur as well

**Comment by dragonwocky** [comment] 2020-11-13 07:30
duplicate of #197

fix will be released soon, best workaround at the moment is:

1. Open notion in your browser
2. Create a new page
3. Click on the 3 dots on the top right and click "Open in Windows app"

**Comment by lensco** [comment] 2020-11-13 08:20
Just experienced Notion not opening on macOS 10.15.7. It bounces once and never launches, console says "Binary is improperly signed".
At first I thought it may be because I changed the icon in the package contents, but I redownloaded the app, changed the icon and it launches fine. But now Notion-Enhancer is no longer working – do I have to reinstall that using the whole regular install procedure?

**Comment by dragonwocky** [comment] 2020-11-13 08:25
Can you guys try uninstalling Notion & the enhancer, then reinstalling Notion and making a copy of `/Applications/Notion.app/Contents/Info.plist`. Then reinstall the enhancer and replace the `/Applications/Notion.app/Contents/Info.plist` file with the copy you made and see if that helps.

**Comment by lensco** [comment] 2020-11-13 09:15
It works by just uninstalling and reinstalling, without replacing the `Info.plist`. I've kept a copy in case it starts acting up again.

**Comment by Davedeji** [comment] 2020-11-13 16:34
> Can you guys try uninstalling Notion & the enhancer, then reinstalling Notion and making a copy of `/Applications/Notion.app/Contents/Info.plist`. Then reinstall the enhancer and replace the `/Applications/Notion.app/Contents/Info.plist` file with the copy you made and see if that helps.

Yeah this worked for me. Thanks

**Comment by jmiao24** [comment] 2020-11-13 17:54
> Can you guys try uninstalling Notion & the enhancer, then reinstalling Notion and making a copy of `/Applications/Notion.app/Contents/Info.plist`. Then reinstall the enhancer and replace the `/Applications/Notion.app/Contents/Info.plist` file with the copy you made and see if that helps.

This also works for me. Thanks a lot!

**Comment by zero9712** [comment] 2020-11-17 15:47
> Can you guys try uninstalling Notion & the enhancer, then reinstalling Notion and making a copy of `/Applications/Notion.app/Contents/Info.plist`. Then reinstall the enhancer and replace the `/Applications/Notion.app/Contents/Info.plist` file with the copy you made and see if that helps.

This isn't working for me, is there another way?

**Comment by romantech** [comment] 2020-12-06 04:34
> Can you guys try uninstalling Notion & the enhancer, then reinstalling Notion and making a copy of `/Applications/Notion.app/Contents/Info.plist`. Then reinstall the enhancer and replace the `/Applications/Notion.app/Contents/Info.plist` file with the copy you made and see if that helps.

I had the same problem, but it worked fine after I did it this way. Thanks!

**Comment by mau-lopez** [comment] 2020-12-11 01:06
This solution worked for me but after restart, again, I could not open Notion. Same "You do not have permissions ..." message

MBP Late 2015 13", Big Sur (11.0.1), Notion 2.0.11

**Comment by Davedeji** [comment] 2020-12-11 02:59
yeah, after reboot mine fails as well

**Comment by Davedeji** [comment] 2020-12-11 03:01
worked for me initially, but I've had to stop using notion enhancer for now.

**Comment by ToPeas** [comment] 2020-12-18 07:04
![image](https://user-images.githubusercontent.com/13310553/102584688-e96f5780-4141-11eb-8ec3-5cee225895e5.png)

same problem after update macOS, and i have more.

mac 2019 16-inch 
macOs Big Sur

**Comment by dragonwocky** [comment] 2020-12-21 00:36
a more reliable solution than what I put above is here: https://github.com/notion-enhancer/notion-enhancer/issues/355

closing this to continue the bug report there since it has better information.

**Closed by dragonwocky** 2020-12-21 00:36 UTC
Labels: bug

**Comment by jimschenchen** [comment] 2021-01-29 06:32
> Can you guys try uninstalling Notion & the enhancer, then reinstalling Notion and making a copy of `/Applications/Notion.app/Contents/Info.plist`. Then reinstall the enhancer and replace the `/Applications/Notion.app/Contents/Info.plist` file with the copy you made and see if that helps.

Thanks, this works for me. macOS Big Sur Version 11.0.1 MacBook Pro (15-inch, 2016)
After installing the notion, I have to open notion once and then copy the Info.plist, or it will not work.

**Comment by sungm2nyeo** [comment] 2021-02-27 19:33
> Can you guys try uninstalling Notion & the enhancer, then reinstalling Notion and making a copy of `/Applications/Notion.app/Contents/Info.plist`. Then reinstall the enhancer and replace the `/Applications/Notion.app/Contents/Info.plist` file with the copy you made and see if that helps.

Does this workaround still apply and work? 

1. Uninstalled both Notion and Notion enhancer (`npm remove -g notion-enhancer` and deleted **.notion-enhancer** folder as well)
2. Reinstalled Notion then opened and closed once. Copied **Info.plist** from the Notion's contents folder.
3. Installed Notion enhancer: 
```
    sudo chmod -R a+wr /usr/local/lib/node_modules
    sudo chmod -R a+wr /usr/local/bin
    sudo chmod -R a+wr /Applications/Notion.app/Contents/Resources
    npm i -g notion-enhancer
```
4. Replaced **Info.plist** file
5. Notion app still would not open so tried `codesign --force --deep --sign - /Applications/Notion.app` but no luck.

Maybe my issue is different because I don't even get any error message at all. Notion just does not open unless the enhancer is uninstalled. I get a "No Available Windows" message if I click on _Show All Windows_ but nothing about the permission or anything. 

I use:
macOS Big Sur ver 11.2.1 on iMac Retrina 5K, 27-inch, 2020 (Intel processor)

**Comment by dragonwocky** [comment] 2021-02-27 21:10
@sungm2nyeo see #437 - notion's update has broken the enhancer.
