### ISSUE TITLE
No cursor with 'Tabs'

### ISSUE THREAD

**Issue by jamezcharazu** [notion-enhancer/notion-enhancer#542] opened 2021-07-26 11:14 UTC
**describe the bug**
There's no typing cursor with 'tabs' enabled. This is still the case when only 'tabs' is enabled.

**expected behaviour**
You should be able to see where you're typing!

**platform**
Windows 10

**Comment by robinpdev** [comment] 2021-07-30 09:52
Duplicate of #400

**Closed** 2021-09-05 05:37 UTC
Labels: bug, duplicate
